### ISSUE TITLE
Implémentation de sgmap/beta.gouv.fr:348

### ISSUE THREAD

**Issue by Morendil** [sgmap/betaGouvBot#1]
Plan d'implémentation révisé suite aux conversations ci-dessous:
- [x] se brancher sur l'API https://beta.gouv.fr/api/v1/authors.json
- [x] une fois par jour, checker les dates de fin
- [x] envoyer un mail pour tous ceux dont les dates sont à J+1 ou J+10

Plan de mise en prod:
- [x] déploiement sur Heroku
- [x] mise en place de la vérification périodique 24h

**Comment by MattiSG** [comment]
> lors d'un push, parcourir /_author et parser le YAML des fichiers .md

👎 

Proposition :

- [ ] Ouvrir une API sur les données en prod.
- [ ] Fetch l'API avec un `cron` une fois par jour, par exemple sur AWS Lambda, ou sur un ∆now, ou sur un serveur à nous.

**Comment by Morendil** [comment]
Oui j'y avais pensé aussi, j'y voyais un bémol: "ouvrir une API" est plus intrusif sur le dépot beta.gouv.fr; il faut créer un layout spécifique pour JSON-ifier la collection _author.

**Comment by Morendil** [comment]
Tu as une objection spécifiquement au fait de déclencher un job lors du push?

**Comment by jdesboeufs** [comment]
Il y a une API sur cette base dans api.gouv.fr. Jette un oeil ;)
Le mar. 11 oct. 2016 à 21:59, Laurent Bossavit <notifications@github.com> a
écrit :

**Comment by Morendil** [comment]
@jdesboeufs Vu, thx. J'avais pas l'astuce layout: null...

**Comment by MattiSG** [comment]
> Tu as une objection spécifiquement au fait de déclencher un job lors du push ?

Simplement que ça ajoute du couplage. Sinon, non.

**Comment by Morendil** [comment]
En fait je suis en train de chercher midi à 14 heures, il suffit de brancher un cron quotidien et d'envoyer une notif via SendGrid si on est à J-1 ou J-10 d'une date de fin.

Ma meilleure idée pour le check périodique est de déployer un mini-service sur Heroku et de l'appeler toutes les 24h avec OnWebChange. Je suis preneur de suggestions plus élégantes, à condition de pouvoir implémenter le service en Sinatra.

**Comment by Morendil** [comment]
Première implémentation en prod; je vais ensuite étudier la PR de @maukoquiroga
