### ISSUE TITLE
Renommer ce dépôt (et l'outil) en beta.gouv.bot

### ISSUE THREAD

**Issue by MattiSG** [sgmap/betaGouvBot#32]
Par uniformité de casse avec beta.gouv.fr.

**Comment by Morendil** [comment]
Ca mérite de creuser un peu la comparaison coût / bénéfice... Pour moi c'est un coût faible (quand même quelques renommages ailleurs que dans ce repo), mais idem pour le bénéfice.

A priori il n'y a pas possibilité [d'acquérir le domaine](http://nic.bot/) correspondant pour l'instant...

On a déjà `beta.ssi` et `beta.wip` - on serait plus uniforme avec `beta.bot` ?

**Comment by MattiSG** [comment]
> Pour moi c'est un coût faible […], mais idem pour le bénéfice.

Complètement  :wink:

> On a déjà beta.ssi et beta.wip - on serait plus uniforme avec beta.bot ?

…ou en passant à `beta.gouv.wip` 😛

**Comment by maukoquiroga** [comment]
```beta.gouv.bt``` ?

**Comment by Morendil** [comment]
A la réflexion je préfèrerais: `ssi.incubateur.net`, `wip.incubateur.net`, `bot.incubateur.net`. Rationale: ce sont des produits qui forment l'infrastructure de `beta.gouv.fr` mais pas des startups, le namespace qui convient est donc `incubateur.net`. (Potentiellement on peut ainsi ouvrir au public des sites sur les sous-domaines correspondants dans un but de documentation.)

Toujours pas convaincu que ça vaille la peine d'y consacrer de l'énergie pour l'instant, mais mon raisonnement est différent: je pense maintenant qu'il y a un [bâton de mikado](https://www.manning.com/books/the-mikado-method) au-dessus, qui est le fonctionnement de `beta.gouv.fr` (fédération d'incubateur de Startups d'Etat, ou autre chose?) voire un autre qui serait le découpage de l'orga Github `sgmap` en plusieurs organisations.

**Comment by MattiSG** [comment]
> le fonctionnement de beta.gouv.fr (fédération d'incubateur de Startups d'Etat, ou autre chose?) voire un autre qui serait le découpage de l'orga Github sgmap en plusieurs organisations.

Oui, oui, oui ! (un simple 👍 ne me semblait pas suffisamment fort :wink: )

**Comment by Morendil** [comment]
Je ferme pour l'instant, à réouvrir quand cette question sera traitée.
