### ISSUE TITLE
Adresser les notifications par mail aux personnes concernées

### ISSUE THREAD

**Issue by Morendil** [sgmap/betaGouvBot#4]
## Option 1

- inférer les emails à partir de fullname (split sur whitespace en supposant, [à tort](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/), "first last")

Problèmes potentiels:

- quid des membres qui n'ont pas ou ne se servent pas du mail @beta.gouv.fr ?
- quid des membres qui ont des noms ne correspondant pas à ce schéma?

## Option 2

- ajouter un champ "email" à la fiche membre avec le mail @beta.gouv.fr explicite ou le mail perso

Problèmes potentiels:

- quid des membres qui n'ont pas ou ne se servent pas du mail @beta.gouv.fr ?
- quid des membres qui ne souhaitent pas publier leur email dans l'API?

**Comment by MattiSG** [comment]
## Option 3

- [ ] Uniformiser les ID des membres à l'adresse email utilisée pour le compte `beta.gouv`, soit `nom.prenom` pour quasiment tout le monde, et l'utilisation d'une redirection pour ceux souhaitant rester anonymes.
- [ ] Documenter cette convention de nommage sur beta.gouv.fr

**Comment by Morendil** [comment]
Et ça marcherait aussi pour https://github.com/sgmap/beta.gouv.fr/issues/299

**Comment by MattiSG** [comment]
Option 3 implémentée via sgmap/beta.gouv.fr#429

**Comment by MattiSG** [comment]
Il faut a priori modifier [`mailer.rb`](https://github.com/sgmap/betaGouvBot/blob/master/lib/betagouvbot/mailer.rb#L9-L16), ce qui implique de passer par un objet [`Personalisation`](https://github.com/sendgrid/sendgrid-ruby/blob/417eb48241f43a1dd5135a761ad6cfa7295ccbc0/examples/helpers/mail/example.rb#L25-L31) dans la gem `sendgrid`, puisque la forme raccourcie actuelle ne prend pas de `cc` en paramètre.

**Comment by MattiSG** [comment]
Pour moi, il faudrait envoyer un mail par contrat arrivant à échéance.

- 21 jours avant : uniquement au destinataire, avec indication de comment mettre à jour en cas de changement, lien vers la page wiki Au revoir si tout est normal, et de contacter `contact@beta.gouv.fr` en cas de difficulté.
- 14 jours avant : même mail avec `contact@beta.gouv.fr` en copie.
- La veille du départ : remerciement et lien vers la page wiki Au revoir cc `contact`.

**Comment by MattiSG** [comment]
@maukoquiroga prend la partie technique.

Je propose les textes suivants :

## 21 jours avant

```
from: bot@beta.gouv.fr
to : {author.id}@beta.gouv.fr
reply-to: contact@beta.gouv.fr
subject: 🗓 Fin de contrat prévue pour dans 3 semaines

Bonjour {author.fullname} !

D'après les données accessibles sur [beta.gouv.fr](https://beta.gouv.fr/equipe), ton contrat actuel arrive à expiration le {author.end | format DD/MM/YYYY}.

Si c'est bien normal, assure-toi de prendre connaissance dès maintenant de [ce qu'il te faudra faire en partant](https://github.com/sgmap/beta.gouv.fr/wiki/Au-revoir).

Si ton contrat a été prolongé et que tes nouvelles dates sont certaines, [mets-les à jour](https://github.com/sgmap/beta.gouv.fr/edit/master/_author/${author.id}.md) en deux minutes tout de suite !

Si quelque chose n'est pas clair, réponds à cet email ou ouvre une conversation dans [#administration](https://startups-detat.slack.com/messages/administation/).

Sans changement de date, un autre rappel sera automatiquement envoyé dans une semaine.

Bonne journée,
Le secrétariat

PS : ce message est envoyé par robot non-[AGI](https://en.wikipedia.org/wiki/Artificial_general_intelligence). En cas de problème, contacter un humain !
```

## 14 jours avant

```
from: bot@beta.gouv.fr
to : {author.id}@beta.gouv.fr
cc: contact@beta.gouv.fr
reply-to: contact@beta.gouv.fr
subject: ⏲ Fin de contrat prévue pour dans 2 semaines

Bonjour {author.fullname} !

D'après les données accessibles sur [beta.gouv.fr](https://beta.gouv.fr/equipe), ton contrat actuel arrive à expiration le {author.end | format DD/MM/YYYY}.

Si c'est bien normal, assure-toi de prendre connaissance dès maintenant de [ce qu'il te faudra faire en partant](https://github.com/sgmap/beta.gouv.fr/wiki/Au-revoir).

Si ton contrat a été prolongé et que tes nouvelles dates sont certaines, [mets-les à jour](https://github.com/sgmap/beta.gouv.fr/edit/master/_author/${author.id}.md) en deux minutes tout de suite !

Si quelque chose n'est pas clair, réponds à cet email ou ouvre une conversation dans [#administration](https://startups-detat.slack.com/messages/administation/).

Sans changement de date, un dernier rappel sera automatiquement envoyé la veille de ton départ.

Bonne journée,
Le secrétariat

PS : ce message est envoyé par robot non-[AGI](https://en.wikipedia.org/wiki/Artificial_general_intelligence). En cas de problème, contacter un humain !
```

## 1 jour avant

```
from: bot@beta.gouv.fr
to : {author.id}@beta.gouv.fr
reply-to: contact@beta.gouv.fr
subject: ⏰ Fin de contrat prévue pour demain

Bonjour {author.fullname} !

D'après les données accessibles sur [beta.gouv.fr](https://beta.gouv.fr/equipe), ton contrat actuel arrive à expiration demain.

C'est le moment de t'assurer que tu as bien coché tous les éléments de la [checklist de départ](https://github.com/sgmap/beta.gouv.fr/wiki/Au-revoir).

On espère que tu as passé un moment positif avec nous !

Bonne journée et à une prochaine,
Le secrétariat

PS : ce message est envoyé par robot non-[AGI](https://en.wikipedia.org/wiki/Artificial_general_intelligence). En cas de problème, contacter un humain !
```

## 1 jour après

```
from: bot@beta.gouv.fr
to : contact@beta.gouv.fr
reply-to: contact@beta.gouv.fr
subject: Contrat expiré

Bonjour les loulous,

{author.fullname} est apparemment parti·e hier.

Il faut s'assurer qu'elle ou il est bien :

- Dans la [team alumni](https://github.com/orgs/sgmap/teams/alumni) sur GitHub.
- Sans droit d'écriture sur des dépôts sur [GitHub](https://github.com/orgs/sgmap/people).
- Sans droit d'écriture sur l'agenda public.
- Sans droit de délégation sur le [manager OVH](https://www.ovh.com/manager/web/#/configuration/email_domain/beta.gouv.fr?tab=EMAILS).
- Passé·e des [mailing-lists](https://www.ovh.com/manager/web/#/configuration/email_domain/beta.gouv.fr?tab=EMAILS) incubateur et contact vers la mailing-list alumni.

Bonne journée,
Le secrétariat

PS : vous voudriez pas me coder 2-3 plugins pour que je fasse tout ça à votre place ? 😬
PPS : ce message est envoyé par robot non-[AGI](https://en.wikipedia.org/wiki/Artificial_general_intelligence). En cas de problème, contacter un humain !
```

**Comment by maukoquiroga** [comment]
Merci @MattiSG pour les textes. On en prend avec @Morendil .

**Comment by Morendil** [comment]
Done.

J'ai doté le bot d'une interface de debug, ainsi [ce lien](http://pure-mesa-18448.herokuapp.com/debug) vous permet de vérifier s'il y a des mails qui partent aujourd'hui et [celui-ci](http://pure-mesa-18448.herokuapp.com/debug2017-01-17) les mails qui partent à une date arbitraire. J'envoie le JSON brut tel que transmis à Sendgrid.

Je n'ai pas voulu faire l'effort d'émettre des mails HTML avec des liens cliquables comme suggéré dans les textes fournis par @MattiSG - il aurait fallu mettre en place un pipeline Markdown -> HTML, j'ai pris l'option de faire du texte brut.

Dans la même logique de flemme, au lieu d'utiliser des objets Personnalisation je génère les méta-données du mail (from, to, subject etc) à partir de templates Liquid. J'ai utilisé plusieurs `to` plutôt qu'un `Cc` parce que ça me semble équivalent, mais on peut faire les deux.

Merci à @maukoquiroga pour le mentoring sur les tests d'intégration avec des mocks, et je reste preneur de tes lumières sur d'éventuels refactorings.
