### ISSUE TITLE
Envoyer les notifications Slack sur le channel #incubateur-secretaria

### ISSUE THREAD

**Issue by MattiSG** [sgmap/betaGouvBot#47]
Les confirmations d'inscription et d'envoi de badge sont aujourd'hui faites dans `#general`. Elles me sembleraient avoir leur place dans le canal réservé au secrétariat plutôt que dans un canal global.

Note : j'ai cherché à faire une PR, mais n'ai trouvé aucune indication dans le code sur comment la connexion à Slack était faite.

**Comment by maukoquiroga** [comment]
Même histoire pour moi hier : il faut aller sur Slack -> /slack commands. Par contre, je ne sais pas si l'on peut définir le canal de response. Il me semble que c'est comme pour /trad -> c'est dans le canal où t'utilises /badge que tu vas recevoir la confirmation. To confirm, though.

**Comment by Morendil** [comment]
Ce n'est pas betaGouvBot qui décide, mais l'utilisateur de la commande: ma lecture de [la doc](https://api.slack.com/slash-commands) est que les réponses sont nécessairement envoyées dans le même channel que celui où on a émis la commande. Si on peut faire autrement j'en serais ravi mais ce n'est pas le cas à ma connaissance. Le wiki précise [explicitement](https://github.com/sgmap/beta.gouv.fr/wiki/Bienvenue) qu'il faut émettre ces commandes dans #incubateur-secretaria.
