### ISSUE TITLE
Ajoute le label « stale » aux issues/PRs beta.gouv.fr qui sont ouvertes depuis X jours

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/betaGouvBot#87]

**Comment by Morendil** [comment]
Je ne sais pas avec quel outil on ajoute les labels "in progress", "in review" etc. mais ça serait plutôt par ces outils de le prendre en charge à mon avis.

Sinon regarde https://github.com/probot/stale - je pense que ça fait le job. Je ferme car à mon avis ce n'est pas une feature de BGB mais réouvre si tu as un raisonnement différent.
