### ISSUE TITLE
Changer dans l'email de notif : /equipe -> /communaute

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/betaGouvBot#88]
<img width="671" alt="capture d ecran 2017-06-16 a 20 06 00" src="https://user-images.githubusercontent.com/329236/27238964-45fae830-52cf-11e7-9956-74c51f89a4d1.png">

**Comment by Morendil** [comment]
Bien vu :)

**Comment by Morendil** [comment]
En fait c'est misleading, on ne trouve pas les dates de départ sur la page Communauté 😉
