### ISSUE TITLE
N'envoyer les badge requests qu'une fois par semaine

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/betaGouvBot#93]
> bien vouloir centraliser ces demandes, et de ne les recevoir qu’une fois par semaine, soit le lundi ou le vendredi matin.

**Comment by Floby** [comment]
je pense que le mieux c'est de coller les demandes de badges avec un flag "todo" dans mongo et de lancer un scheduled job perso (ceux de heroku sont peu fiables) une fois par semaine.

[ ] Stocker les demandes en base avec un flag "todo"
[ ] Lancer un job une fois par semaine sans heroku scheduled jobs
[ ] Envoyer un mail groupant les demandes marquées à faire
[ ] Passer les commandes traitées à "done"
[ ] Virer les enregistrement des demandes > 3 mois

**Comment by Morendil** [comment]
Sinon on peut aussi utiliser l'API SendGrid pour mettre les mails en file d'attente jusqu'au lundi suivant la date de la demande - on reste stateless, et le coût en complexité supplémentaire est sans doute moindre.

Les scheduled job de Heroku donnent entière satisfaction depuis des mois, cela dit.

**Comment by Floby** [comment]
J'ignorais cette feature de sendgrid.
ça vaut le coup d'essayer

**Comment by maukoquiroga** [comment]
À la lumière des nouveaux éléments, est-ce que cet issue reste encore d'actualité ?
